---
title: "D2"
author: "Jeremiah Theisen"
date: "2024-09-26"
output: pdf_document
---

## 3.2.1
a. 6m
b. 2 sd above
c. 3m below
d. 1 sd below
e. 5m above
f. 8/3 = 1 2/3 = 1.6666666 sd

## 3.2.2 SKIP 

## 3.2.3 SKIP

## 3.2.4  
a. 
```{r} 
pnorm(130, mean=120, sd=25)
``` 
b. 0.3445783
c. 
```{r} 
pnorm(100, mean=120, sd=25)
``` 
d. 0.4435663 
e.
```{r}
qnorm(0.1, mean=120, sd=25)
``` 
f.
```{r}
qnorm(0.95, mean=120, sd=25)
``` 
P(Z < 120 + k) = 0.95 

g.
k = 41.1213

## 3.2.5  
a. 
```{r}
n=1000
ahiweight=rnorm(n,mean=120, sd=25)
hist(ahiweight)
```
b. 
```{r}
length(which(ahiweight>150))/n
```
c.
```{r}
X0=161.1213
length(which(ahiweight>X0))/n
``` 
d.
```{r} 
length(which(100>ahiweight & ahiweight>50))/n
```
e. 
```{r} 
k=161.1213
length(which(120+k>ahiweight & ahiweight>120-k))/n
```

## 3.2.6 
a. 
```{r}
pnorm(6, mean=4.5, sd=1)
``` 
P(Z > 6) = 0.0668072

b. 
```{r}
qnorm(0.05, mean=4.5, sd=1)
```
c. 
```{r}
pnorm(3, mean=4.5, sd=1)
pnorm(4, mean=4.5, sd=1)
```  
0.2417303

d. 
```{r} 
qnorm(0.95, mean=4.5, sd=1)
``` 
k = 1.644854

