---
title: "PPractice"
author: "Jeremiah Theisen"
date: "2024-09-19"
output: pdf_document
---

## P1 

```{r} 
names(chickwts)
``` 
1. a
```{r}
length(which(chickwts$feed=="soybean"))
length(which(chickwts$feed=="meatmeal"))

``` 
b. P(S) = 14/71 = 0.197
P(M) = 11/71 = 0.1549

c. 
```{r}
ndex = sample(1:nrow(chickwts), 20)
samp=chickwts[index,]
table(samp$feed)
``` 
d. P(M|T) = 5/20 = 0.25
P(S|T) = 4/20 = 0.2

e. The proportion in the sample was significantly higher. 

## P2 
2a. P(R) = 26/52 => 1/2 => 0.5 
b. P(F) = 12/52 => 3/13 => 0.2307 
c. P(F and R) = 6/52 => 3/26 => 0.11538 
d. They are independent because 
  i. P(R)P(F) = P(R and F) because 26/52 * 12/52 = 0.11538 
  ii. P(R|F) = 0.11538/0.2307 = 0.5, which is P(R) 
e. This would be dependent on the outcome of the first event, because P(F) initially equals 12/52, but after a card is drawn, it can equal either 12/51 or 11/51 depending on if the card drawn was a face card or not. 

## P3 
3. P(B) = 0.7333 

## P4 
4.
a. -1, 2, 74, 9999

b. E(X) = -0.37591 
c. 
```{r}
ticketwinnings = sample(c(-1, 2, 74, 9999), 1000000, replace
= TRUE, prob = c(0.8499, 0.15, 0.001, 0.00001))
hist(ticketwinnings)
``` 
d. 
```{r}
mean(ticketwinnings)
```
## P5 
5. E(Z) = -1.8
